const CUSTOM_APP_CREATOR_GUIDE_LINES = [
  "# 小手机自定义 APP 制作说明",
  "",
  "## 1. 这是什么",
  "",
  "你正在为\"仿真 AI 互动小手机\"制作一个能安装进【应用市场】的自定义 APP，可以是购物、打卡、短信、外卖、论坛、日记、工具箱等独立应用。",
  "",
  "**心智模型**：一个 APP 就是一个跑在小手机 iframe 沙盒里的网页。它**不能**直接读取宿主内部数据，只能通过小手机提供的安全 SDK（`window.AiPhone`）请求能力——读写自己的私有数据、读取角色、让角色生成内容、向聊天室发卡片等。",
  "",
  "```",
  "┌─────────────── 小手机宿主 ───────────────┐",
  "│  角色 / 记忆 / 聊天历史 / 统一预设系统     │",
  "│        ▲ 通过 SDK 请求         │ 回调      │",
  "│  ┌─────┴───────────────────────▼──────┐  │",
  "│  │   你的 APP（iframe 沙盒）           │  │",
  "│  │   index.html + manifest + 声明文件  │  │",
  "│  └─────────────────────────────────────┘  │",
  "└────────────────────────────────────────────┘",
  "```",
  "",
  "一个 APP 包由三类东西组成：",
  "",
  "* **前端**：`index.html`（必需）+ `assets/` 静态资源。",
  "* **manifest.json**：声明 APP 身份、权限、扩展入口。",
  "* **声明文件（可选）**：`presets.json`，声明 APP 场景的提示词条目，和角色生成链路联动。",
  "",
  "> 最快验证：只写一个 `index.html` 就能做原型测试。正式发布再补 `manifest.json` 和 `icon.png`。",
  "",
  "---",
  "",
  "## 2. 应用包结构",
  "",
  "最终由用户压缩成 `.zip` 上传。最小结构：",
  "",
  "```txt",
  "my-app/",
  "├── manifest.json",
  "├── index.html",
  "├── icon.png",
  "└── assets/",
  "```",
  "",
  "复杂 APP 可在根目录额外放声明文件。**没有相关需求就不要生成**；一旦生成，必须在 `manifest.resources` 里声明它们。",
  "",
  "|文件|职责（一句话）|",
  "|-|-|",
  "|`manifest.json`|APP 身份、权限、扩展入口。正式发布必需|",
  "|`index.html`|前端入口。原型测试时可单独存在|",
  "|`icon.png`|APP 图标。正式发布建议必需|",
  "|`assets/`|图片、音频、字体等静态资源|",
  "|`presets.json`（可选，需要自定义 APP 内角色有全局全量记忆、日程信息、绑定世界书等时使用）|提示词条目，用于约束角色输出内容、格式等。会进入宿主提示词预设管理系统，用户可以自定义编辑。<br />提示词预设管理系统中已有角色的全量信息，调用 `AiPhone.ai.generate` 后，APP 定义的预设条目将会追加在后面，共同组成提示词。|",
  "",
  "> 声明文件的详细写法见 [4.2 声明文件 JSON 写法](#42-声明文件-json-写法)。",
  "",
  "---",
  "",
  "## 3. manifest.json 字段参考",
  "",
  "`manifest.json` 必须是 JSON 对象。完整示例：",
  "",
  "```json",
  "{",
  "  \"sdkVersion\": \"1.0\",",
  "  \"id\": \"waimai.demo\",",
  "  \"name\": \"浮岛外卖\",",
  "  \"version\": \"1.0.0\",",
  "  \"author\": \"你的名字\",",
  "  \"description\": \"一个可以浏览店铺、选择餐品，并和聊天室外卖卡片联动的 APP。\",",
  "  \"icon\": \"icon.png\",",
  "  \"entry\": \"index.html\",",
  "  \"permissions\": [",
  "    \"app.data.read\",",
  "    \"app.data.write\",",
  "    \"characters.read\",",
  "    \"chat.sendCard\",",
  "    \"chat.requestReply\",",
  "    \"ai.generate\",",
  "    \"ui.toast\"",
  "  ],",
  "  \"resources\": {",
  "    \"presets\": [\"presets.json\"]",
  "  },",
  "  \"extensions\": {",
  "    \"chat\": {",
  "      \"directives\": [",
  "        {",
  "          \"id\": \"waimai-order\",",
  "          \"label\": \"外卖下单\",",
  "          \"syntax\": \"[外卖下单:收餐人:店铺:餐品:备注]\",",
  "          \"description\": \"当角色想主动给用户点一份外卖，并让用户确认下单时使用。\",",
  "          \"card\": {",
  "            \"appLabel\": \"浮岛外卖\",",
  "            \"title\": \"确认外卖订单\",",
  "            \"subtitle\": \"{{店铺}}\",",
  "            \"body\": \"{{餐品}} · {{备注}}\",",
  "            \"status\": \"待确认\",",
  "            \"accentColor\": \"#f97316\",",
  "            \"sections\": [{",
  "              \"title\": \"订单信息\",",
  "              \"rows\": [",
  "                { \"label\": \"收餐人\", \"value\": \"{{收餐人}}\" },",
  "                { \"label\": \"店铺\", \"value\": \"{{店铺}}\" },",
  "                { \"label\": \"餐品\", \"value\": \"{{餐品}}\" },",
  "                { \"label\": \"备注\", \"value\": \"{{备注}}\" }",
  "              ]",
  "            }],",
  "            \"actions\": [{ \"label\": \"确认下单\" }]",
  "          }",
  "        }",
  "      ],",
  "      \"plusActions\": [",
  "        {",
  "          \"id\": \"order-food-for-character\",",
  "          \"label\": \"给TA点外卖\",",
  "          \"entry\": \"order-food-for-character\",",
  "          \"presentation\": \"panel\",",
  "          \"panelHeight\": \"72vh\",",
  "          \"description\": \"从聊天室打开外卖选择面板，给当前聊天对象点一份外卖。\"",
  "        }",
  "      ]",
  "    }",
  "  }",
  "}",
  "```",
  "",
  "### 3.1 顶层字段",
  "",
  "* **id**：可选的开发者标识，只能用英文、数字、点、下划线、短横线。安装和市场发布会生成自己的内部 APP ID，**创作者不需要手动保证全局唯一**。",
  "* **permissions**：只声明实际会用到的能力（清单见 [第 6 节](#6-权限清单)）。需要外部 API、语音、工具、钱包、定时任务时，再按需增加对应权限和字段。",
  "",
  "### 3.2 resources：只声明包里真实存在的文件",
  "",
  "图片、音频、字体等静态文件放 `assets`。没有某类文件就不要写那一项：",
  "",
  "```json",
  "\"resources\": {",
  "  \"presets\": [\"presets.json\"],",
  "  \"assets\": [\"assets/menu-cover.png\"]",
  "}",
  "```",
  "",
  "* `assets` 声明图片、音频、字体等静态资源路径，APP 运行时可用 `AiPhone.app.getAssetUrl(\"assets/menu-cover.png\")` 拿到可访问地址。",
  "* 如果需要注册 APP 工具，不要额外创建 `tools.json`，请直接写在 `manifest.extensions.tools`。",
  "* 如果 APP 有自己的语音配置、音色列表或提示音文件，可放在 `assets` 或 APP 私有数据里，再由 APP 自己读取。",
  "",
  "### 3.3 extensions（可选）",
  "",
  "`extensions.chat` 用来把 APP 接到小手机最核心的 APP ——聊天 APP。其中，富媒体指令是角色可以使用的操作，现有的包括模拟发红包、分享音乐、发送表情包等，这里注册的新富媒体指令会追加在后面；+ 号面板是用户在输入栏里使用的面板，将 APP 的相关操作放置在这里，可以让用户在聊天 APP 里更方便快捷地调用自定义 APP 的功能。",
  "",
  "> APP 的聊天室扩展统一写在 `extensions.chat.*`，后台事件监听统一写在 `extensions.events`。",
  "",
  "#### extensions.chat.directives —— 富媒体指令",
  "",
  "给角色注册\"一段它可以直接写进聊天 APP 回复的文本标记\"，格式就是 `syntax` 里定义的样子（如 `[外卖下单:收餐人:店铺:餐品:备注]`）。这个富媒体指令用于自定义 APP 和小手机里的聊天 APP 联动。",
  "",
  "* 配好后，角色生成回复前会收到这条可用指令说明。",
  "* 角色在回复里写出它时，宿主自动把标记渲染成你这个 APP 的卡片，并作为一条角色行为写进 AI 可见的聊天历史。",
  "* `card` 可选，用来定制这条指令解析出的卡片，字段和 `AiPhone.chat.sendCard({ card })` 使用同一套布局能力：`title`、`subtitle`、`body`、`sections`、`actions`、`accentColor`、`html`、`height` 等。",
  "* `card` 字符串里可以使用指令参数占位符：`{{arg1}}`、`{{参数1}}`，以及按 `syntax` 命名的 `{{收餐人}}`、`{{店铺}}` 等；不写 `card` 时使用宿主默认卡片模板。",
  "",
  "如果 APP 不只是想把指令渲染成卡片，还想在角色输出该指令后立刻同步数据或执行动作，例如角色发出 `[漂流瓶:内容]` 后，漂流瓶 APP 自动把这条漂流瓶写入自己的数据库，那么需要同时使用事件监听。",
  "",
  "做法是：",
  "",
  "1. 在 `extensions.chat.directives` 里声明富媒体指令，负责告诉角色可用格式，并让宿主把输出渲染成卡片。",
  "2. 在 `extensions.events` 里声明监听 `chat.message.created`。",
  "3. 在 APP 代码里用 `AiPhone.on(\"chat.message.created\", handler)` 监听新聊天消息。",
  "4. handler 里判断这条消息是否来自角色、是否包含本 APP 的富媒体指令；如果匹配，就由 APP 自己决定写数据库、发通知、更新卡片或执行其他动作。",
  "",
  "如果希望 APP 没打开时也能监听，`extensions.events` 里要写 `background: true`。",
  "",
  "如果只需要用户点击卡片后再处理，就不需要事件监听，直接通过卡片打开 APP 后处理即可。",
  "",
  "#### extensions.chat.plusActions —— + 号面板入口",
  "",
  "把 APP 功能注册到用户聊天室的 + 号面板。",
  "",
  "**presentation（展示方式，默认 `panel`）**：",
  "",
  "|值|效果|",
  "|-|-|",
  "|`panel`|聊天内底部面板（`panelHeight` 只对它生效）|",
  "|`modal`|聊天内居中弹窗|",
  "|`fullscreen` / `app`|打开完整 APP 页面|",
  "|`none`|不显示 UI，只让 APP 代码执行|",
  "",
  "**APP 收到的字段**：用户点击后 `AiPhone.app.getLaunchContext()` 返回 `source=\"chat_plus_action\"`、`sessionId`、`characterId`、`actionId`、`entry`、`data`、`directiveId`、`presentation` 等。`entry` 只告诉 APP 当前要渲染哪个内部界面/执行哪个流程；真正的 UI、用户操作、写入聊天的文本、是否触发角色回复，都由 APP 自己决定。",
  "",
  "**完成后可做**：调用 `AiPhone.chat.sendCard` / `writeHistory` / `requestReply` 写回当前聊天，或 `AiPhone.app.close()` 关闭面板。如果这个入口打开后还要请求 LLM，由 APP 自己在 `AiPhone.ai.generate({ appTags })` 里决定本次生成使用什么标签。",
  "",
  "**常用字段**：`id`（入口标识）、`label`（面板里显示的名字）、`entry`（内部界面标识）、`presentation`、`panelHeight`、`data`（传给 APP 的自定义 JSON）、`directiveId`（关联某条富媒体指令）。",
  "",
  "#### extensions.tools —— 角色可调用的 APP 工具",
  "",
  "APP 工具用于和小手机内的聊天 APP 联动。声明角色可以调用的真实动作后，角色可以在聊天 APP 中调用该动作。例如日程 APP 可以注册修改日程、添加日程、删除日程工具，这样角色在聊天 APP 里也可以通过调用工具与自定义 APP 联动；此外，其他用户做的自定义 APP 也可以通过工具调用与你做的自定义 APP 联动。",
  "",
  "工具一般只用于当你觉得小手机里的聊天 APP 需要与你的自定义 APP 联动的时候。如果只是自定义 APP 内部逻辑，通常无需调用工具，除非你明确希望角色在你的 APP 里也能自主调用工具，例如在短信 APP 里希望角色能调用 MCP 工具等。",
  "",
  "每个工具要有 `name`、`description`、参数结构和 `handler` 名；APP 代码里用 `AiPhone.tools.handle(handlerName, fn)` 实现真正动作。角色在聊天 APP 里调用你的自定义 APP 工具时，如果你的自定义 APP 没打开，宿主会临时启动隐藏运行环境执行同一个 handler，完成后自动销毁。隐藏运行环境默认最多保留 5 分钟；确实需要更久时，可在工具声明里写 `timeoutMs`，最高 30 分钟。",
  "",
  "* `visibility: \"private\"` → 仅本 APP 内部生成可用，不进入“设置 → 聊天工具箱”。",
  "* `visibility: \"shared\"` → 共享给普通聊天和其他 APP，进入“设置 → 聊天工具箱”。",
  "* 工具是否真的对角色可见，由同场景 tags 的预设条目里的 `{{tools}}` 决定。`{{tools}}` 是一个宏变量，会把宿主可用工具及其用法注入。",
  "",
  "详细写法和实现见 [5.11 注册和调用 APP 工具](#511-注册和调用-app-工具)。",
  "",
  "#### extensions.events —— 监听宿主事件",
  "",
  "声明 APP 运行时要监听的宿主事件。推荐对象数组：",
  "",
  "```json",
  "\"events\": [",
  "  {",
  "    \"event\": \"chat.message.created\",",
  "    \"entry\": \"events\",",
  "    \"background\": true,",
  "    \"description\": \"监听聊天新消息；background 为 true 时，APP 未打开也会临时运行后台 handler。\"",
  "  }",
  "]",
  "```",
  "",
  "* `event`：事件名；`entry`：你自己的内部入口名，方便区分用途；`background`：为 `true` 时，APP 未打开也允许宿主临时启动隐藏运行环境，把事件交给 APP 自己的 `AiPhone.on` handler 处理；`timeoutMs`：可选，仅控制隐藏运行环境最长保留时间，默认 5 分钟，最高 30 分钟；`description`：仅说明。",
  "* 导入器兼容 `[\"chat.message.created\"]` 字符串简写，新包推荐对象写法。",
  "",
  "---",
  "",
  "## 4. 声明文件与角色生成链路",
  "",
  "声明文件用于 `AiPhone.ai.generate` 这条 APP 内角色生成链路。APP 调用 `AiPhone.ai.generate({ characterId, appTags })` 时，宿主会按当前角色、当前 APP 和 `appTags`，选择需要进入本次生成的预设条目。",
  "",
  "* `presets.json`：LLM提示词条目，声明角色输出场景，约束角色按该场景的规则和格式输出。",
  "",
  "### 4.1 声明文件如何参与 `AiPhone.ai.generate`",
  "",
  "**presets.json 如何参与生成链路**：",
  "",
  "小手机里有很多 APP、普通聊天、游戏、工具。为了让 APP 共享用户人设、角色人设、记忆等内容，小手机里设计了一套预设系统。里面包括**通用条目及场景条目**，最终按照预设系统里的顺序组装。每个 APP 里，只要涉及到角色输出，都走相同的预设提示词组装链路，以确保角色设定、记忆、日程等在不同 APP 里是稳定的。",
  "",
  "通用条目包括：角色设定、角色性格、用户人设、核心记忆、长期记忆、全局事件流、世界书等。以上条目通常是占位，在实际组装中会被替换为该角色的真实内容。",
  "",
  "场景条目包括：聊天线上输出条目、剧情模式输出条目、生成日记输出条目等。场景条目的意义在于控制输出格式，让 AI 理解当前场景。例如，发朋友圈条目会告诉角色“你正在使用微信朋友圈功能”，并约定输出 `[朋友圈]...[/朋友圈]` 这样的格式。",
  "",
  "发朋友圈的最终 LLM 提示词结构是：通用条目（用以提供角色核心人设、世界观、记忆等）+ 场景条目（用以让 AI 理解输出场景及格式）。APP 在收到 AI 输出后，再对结果进行处理。",
  "",
  "预设系统仅用于角色输出链路。如果没有预设系统，你要获取角色回复，就需要将角色的完整人设、世界书、记忆、日程、用户人设等逐项获取，然后再追加场景提示词，发送给 LLM。预设系统的意义在于：你只需要写一个场景条目，其余角色人设、世界书、记忆、用户人设等已经在预设中存在，不再需要逐项获取然后手动组装。调用 `AiPhone.ai.generate` 并传入你写的那个场景预设的 `appTags` 后，角色将自动获取全量人设、记忆等，并按照该场景的规则和格式输出。",
  "",
  "**presets.json 的 tags 选择规则**：为了在不同场景下使用不同的场景条目，防止条目混乱，我们用 tags 区分场景条目。例如发朋友圈的场景预设可以使用 `['moments', 'post']`，短信回复的场景预设可以使用 `['sms', 'reply']`。",
  "",
  "每个提示词条目可带一组 tags。本次生成传入 `appTags` 后，只有「条目的 tags ⊆ 本次 appTags」的条目才会进入提示词。宿主内置的通用条目通常没有 tags，会进入所有适用链路。APP 自带的 `presets.json` 条目通常要写 tags。",
  "",
  "换句话说：条目要求的每一个 tag，都必须出现在本次 `appTags` 里。",
  "",
  "例（本次 `appTags = [\"sms\", \"reply\"]`）：",
  "",
  "|条目 tags|是否进入|原因|",
  "|-|-|-|",
  "|无|✅|通用条目，不按场景过滤|",
  "|`[\"sms\"]`|✅|是 appTags 的子集|",
  "|`[\"sms\", \"reply\"]`|✅|两个 tag 都在 appTags 里|",
  "|`[\"sms\", \"proactive\"]`|❌|`proactive` 不在本次 appTags 里|",
  "",
  "**presets.json 的 tags 书写约定**：",
  "",
  "* 必须是英文数组，推荐 `[主功能, 子场景]`，如 `[\"sms\", \"reply\"]`、`[\"sms\", \"proactive\"]`、`[\"dungeon\", \"scene\"]`。",
  "* tags 用于场景过滤，推荐使用稳定的英文场景标识。",
  "* 富媒体指令 `directives` 和 + 号面板 `plusActions` 不依赖这套 tags 过滤。它们可以用 `entry`、`directiveId`、`data` 标识功能；只有预设和 `AiPhone.ai.generate({ appTags })` 才需要按这里的规则严格对应。",
  "",
  "短信 APP 里有两种需要角色生成文本的场景：",
  "",
  "|场景|appTags|用途|",
  "|-|-|-|",
  "|短信回复|`[\"sms\", \"reply\"]`|用户在短信 APP 里给角色发短信，角色根据短信内容和关系语境回复|",
  "|主动短信|`[\"sms\", \"proactive\"]`|APP 根据某个事件、时间或状态，让角色主动给用户发一条短信|",
  "",
  "对应地，`presets.json` 可以写两条预设，tags 分别为上面两组：",
  "",
  "* “短信回复”预设：约束角色用短信语气回复，内容短一点，像真实手机短信，并约定前端可解析的输出格式。",
  "* “主动短信”预设：约束角色主动发消息时要有明确动机，不能像普通聊天一样无限展开，并约定前端可解析的输出格式。",
  "",
  "APP 调用 `AiPhone.ai.generate` 并传 `appTags: [\"sms\", \"reply\"]` 时，提示词为通用条目 + “短信回复”预设；传 `appTags: [\"sms\", \"proactive\"]` 时，提示词为通用条目 + “主动短信”预设。",
  "",
  "**输出后处理**：`ai.generate` 只返回文本。如果预设约定了角色输出某种固定标记（如 `[状态:地点=...;时间=...]`），APP 拿到 `result.text` 后直接在自己的 JS 里解析、渲染成卡片或状态栏即可，不需要向宿主注册任何规则。",
  "",
  "**世界书**：角色在绑定设置里配置的世界书会自动进入生成链路，APP 不需要做任何事。APP 自己的场景背景直接写进预设条目。",
  "",
  "### 4.2 声明文件 JSON 写法",
  "",
  "#### presets.json 最小结构",
  "",
  "每条预设都是一段 LLM 提示词条目，用来约束角色在当前 APP 输出中的内容、语气和格式。",
  "",
  "```json",
  "{",
  "  \"presets\": [",
  "    {",
  "      \"id\": \"sms-reply-style\",",
  "      \"name\": \"短信回复\",",
  "      \"content\": \"你正在短信 APP 中回复用户。请以当前角色身份写一条自然短信，语气比普通聊天更短、更像真实手机消息。输出格式固定为：[短信回复:内容]。\",",
  "      \"enabled\": true,",
  "      \"tags\": [\"sms\", \"reply\"]",
  "    },",
  "    {",
  "      \"id\": \"sms-proactive-style\",",
  "      \"name\": \"主动短信\",",
  "      \"content\": \"你正在短信 APP 中主动给用户发一条短信。必须有明确动机，内容短而自然，不要像普通聊天一样连续追问。输出格式固定为：[主动短信:内容]。\",",
  "      \"enabled\": true,",
  "      \"tags\": [\"sms\", \"proactive\"]",
  "    }",
  "  ]",
  "}",
  "```",
  "",
  "---",
  "## 5. SDK 参考",
  "",
  "### 5.1 入口与约定",
  "",
  "```js",
  "const api = window.AiPhone;        // 主入口",
  "// const api = window.AiPhoneApp;  // 宿主也兼容这个别名",
  "```",
  "",
  "所有接口都是异步 Promise。",
  "",
  "### 5.2 速查表（能力 → 方法 → 所需权限）",
  "",
  "|能力|主要方法|所需权限|",
  "|-|-|-|",
  "|读取 APP 信息|`app.getManifest` / `getCapabilities` / `getLaunchContext` / `close`|无|",
  "|私有数据库|`db.create` / `list` / `get` / `update` / `delete`|`app.data.read` / `app.data.write`|",
  "|读取角色|`characters.list` / `get` / `readState` / `writeState` / `readRelations`|`characters.read` / `characters.state.*` / `characters.relations.read`|",
  "|用户资料|`user.getProfile` / `getPersona` / `getPreferences`|`user.profile.read` / `user.persona.read` / `user.preferences.read`|",
  "|外部 API|`network.fetch`|`network.fetch`（+ manifest `network.allowedDomains`）|",
  "|角色生成文本|`ai.generate`|`ai.generate`|",
  "|AI 生图|`ai.generateImage`|`ai.generateImage`|",
  "|通用模型|`ai.chat` / `ai.embed` / `ai.classify`|`ai.chat` / `ai.embed` / `ai.classify`|",
  "|语音|`voice.readProfiles` / `tts` / `stt` / `record` / `clone`|`voice.readProfiles` / `voice.tts` / `voice.stt`(`record` 同权限) / `voice.clone`|",
  "|音频播放(宿主代播)|`voice.play` / `stopPlayback` / `pausePlayback` / `resumePlayback`|`voice.tts`|",
  "|日程|`calendar.read` / `create` / `update` / `write`|`calendar.read` / `calendar.write`|",
  "|世界书|`world.list` / `get` / `read`|`world.read`|",
  "|媒体|`media.pick` / `save`|`media.pick` / `media.save`|",
  "|定位（宿主代理）|`geo.get` / `geo.watch` / `geo.clearWatch` + `AiPhone.on(\"geo.position\", …)`|`geo.read` / `geo.watch`（持续定位事件需 manifest 声明 `geo.position`）|",
  "|媒体库(大文件存储)|`media.put` / `get` / `delete`|`app.data.write` / `app.data.read`|",
  "|APP 工具|`tools.handle` / `invoke`|`chat.tools`|",
  "|发卡片/更新卡片|`chat.sendCard` / `updateCard`|`chat.sendCard`（或 `chat.write`）|",
  "|写聊天历史|`chat.writeHistory`|`chat.write` 或 `chat.sendMessage`|",
  "|请求角色回复|`chat.requestReply`|`chat.requestReply`|",
  "|打开聊天室|`chat.openConversation`|—|",
  "|联系人状态|`chat.setContactState` / `unblock` / `unmute`|`chat.contacts.write`|",
  "|读聊天历史|`chat.getCurrentSession` / `readHistory`|`chat.read`|",
  "|监听事件|`AiPhone.on(\"chat.message.created\", …)`|`chat.read` 或 `chat.read.background`（+ manifest 声明事件）|",
  "|读记忆|`memory.readCore` / `readLongTerm` / `readShortTerm` / `search`|`memory.read*` / `memory.search`|",
  "|写记忆|`memory.add` / `addTimeline`|`memory.write`|",
  "|建议记忆|`memory.suggest`|`memory.suggest`|",
  "|UI 提示|`ui.toast` / `showNotification` / `confirm`|`ui.toast` / `ui.notification`|",
  "|通知/红点|`notifications.create` / `getBadge` / `setBadge` / `clearBadge` / `list` / `markAllRead`|`notifications.read` / `notifications.write`|",
  "|定时任务|`tasks.schedule`|`tasks.schedule`（+ 各 action 自身权限）|",
  "|钱包|`wallet.get` / `pay`|`wallet.read` / `wallet.pay`|",
  "|桥接现实（见 5.25）|`bridge.send` / `readState` / `tools.invoke(快捷动作)` + `AiPhone.on(\"bridge.data\", …)`|`bridge.send` / `bridge.read` / `chat.tools`（事件仅需 manifest 声明）|",
  "|多人联机（见 5.26）|`room.create` / `join` / `send` / `setState` / `kick` + `cloud.put` / `list` / `takeRandom` + `AiPhone.on(\"room.*\", …)`|`online.play`（房间事件需 manifest 声明）|",
  "",
  "### 5.3 读取 APP 信息",
  "",
  "```js",
  "const manifest = await AiPhone.app.getManifest();",
  "const capabilities = await AiPhone.app.getCapabilities();",
  "const launchContext = await AiPhone.app.getLaunchContext();",
  "await AiPhone.app.close();",
  "```",
  "",
  "`launchContext` 取决于打开方式：",
  "",
  "* 从聊天里的富媒体卡片进入：含 `source`、`messageId`、`sessionId`、`directiveId`、`directiveLabel`、`directiveArgs`、`directiveRaw`、`summary` 等。",
  "* 从 + 号面板进入：含 `source=\"chat_plus_action\"`、`sessionId`、`characterId`、`actionId`、`entry`、`data`、`appTags`、`presentation` 等。",
  "* 普通桌面打开：通常为 `null`。",
  "",
  "### 5.4 私有数据库",
  "",
  "这些数据只属于当前 APP；卸载 APP 时，用户选择删除数据才会清掉。",
  "",
  "```js",
  "const item = await AiPhone.db.create(\"orders\", { title: \"冬阴功汤\", status: \"draft\" });",
  "// 注意:音频/图片等大文件不要以 dataURL 存进记录,先 media.put 换引用(见 5.10)",
  "const list = await AiPhone.db.list(\"orders\", { limit: 100 });",
  "const one  = await AiPhone.db.get(\"orders\", item.id);",
  "await AiPhone.db.update(\"orders\", item.id, { status: \"paid\" });",
  "await AiPhone.db.delete(\"orders\", item.id);",
  "```",
  "",
  "提供 create / list / get / update / delete，**不提供 upsert**。要保存设置时，先 `list` 找已有记录 id 再 `update`，找不到再 `create`。",
  "",
  "### 5.5 读取角色",
  "",
  "很多聊天接口都需要 `characterId`。推荐先写一段\"当前角色获取\"逻辑：从卡片/+ 号面板打开时优先用 `launchContext.characterId`；从桌面打开时用 `characters.list()` 做角色选择界面，让用户选中后保存为 `selectedCharacterId`。",
  "",
  "```js",
  "const launchContext = await AiPhone.app.getLaunchContext();",
  "const characters = await AiPhone.characters.list();",
  "const selectedCharacterId = launchContext?.characterId || characters[0]?.id;",
  "if (!selectedCharacterId) throw new Error(\"请先创建或选择一个角色\");",
  "",
  "const character = await AiPhone.characters.get(selectedCharacterId);",
  "const state = await AiPhone.characters.readState({ characterId: selectedCharacterId });",
  "const relations = await AiPhone.characters.readRelations({ characterId: selectedCharacterId });",
  "await AiPhone.characters.writeState({",
  "  characterId: selectedCharacterId,",
  "  stateValues: [{ name: \"好感度\", value: 72 }]",
  "});",
  "```",
  "",
  "`list`/`get` 需 `characters.read`；`readState`/`writeState` 需 `characters.state.read`/`characters.state.write`；`readRelations` 需 `characters.relations.read`。",
  "",
  "### 5.6 读取用户资料和人设",
  "",
  "用户资料和人设是用户的角色面具，也就是用户在聊天/剧情互动中扮演的角色。如果不用 `AiPhone.ai.generate`，而是自己组装提示词让角色生成，必须将用户资料和人设传入，否则角色将不知道用户的面具身份。",
  "",
  "```js",
  "const profile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const persona = await AiPhone.user.getPersona({ characterId: selectedCharacterId });",
  "const preferences = await AiPhone.user.getPreferences({ characterId: selectedCharacterId });",
  "console.log(profile.name, persona.text, preferences.text);",
  "```",
  "",
  "分别需 `user.profile.read` / `user.persona.read` / `user.preferences.read`。",
  "",
  "### 5.7 访问外部 API",
  "",
  "只能访问 manifest `network.allowedDomains` 中声明的域名。支持精确域名和 `*.example.com` 通配子域名，**不允许** localhost 或内网地址。",
  "",
  "`AiPhone.network.fetch` 默认由浏览器客户端直连目标 API，不占用站点服务端函数额度。如果目标接口没有开放 CORS，直连会失败；确实需要服务端代理时，才在单次请求里显式传 `proxy: true`，或在 manifest 写 `network.mode: \"proxy\"`。`timeoutMs` 可选，不传时宿主不主动截断；传入后只影响本次请求。走代理时 `timeoutMs` 不能超过 `/api/tool-proxy` 的 120 秒保护。",
  "",
  "```js",
  "const response = await AiPhone.network.fetch({",
  "  url: \"https://api.example.com/orders\",",
  "  method: \"POST\",",
  "  headers: { \"Content-Type\": \"application/json\" },",
  "  body: { dish: \"冬阴功汤\", count: 1 },",
  "  timeoutMs: 30000",
  "});",
  "if (response.ok) console.log(response.json || response.text);",
  "```",
  "",
  "```js",
  "// 只有目标 API 不能浏览器直连、且你接受走站点服务端代理时才这样写",
  "const response = await AiPhone.network.fetch({",
  "  url: \"https://api.example.com/orders\",",
  "  method: \"POST\",",
  "  body: { dish: \"冬阴功汤\", count: 1 },",
  "  proxy: true,",
  "  timeoutMs: 60000",
  "});",
  "```",
  "",
  "需 `network.fetch`，且 manifest 必须声明 `network.allowedDomains`。",
  "",
  "### 5.8 让角色生成文本",
  "",
  "`ai.generate` 按指定角色组装一次**完整提示词**，但只返回文本，不自动发到聊天室。它保留角色人设、用户人设、核心记忆、长期记忆、短期记忆事件流等基础上下文；传入 `appTags` 时还会加入匹配的 APP 预设条目（规则见 [第 4 节](#4-声明文件与角色生成链路)）。",
  "",
  "普通单轮任务只传 `instruction`；如果 APP 自己有多轮剧情、短信线程、客服对话等内部记录，把这些记录作为 `messages` 传入。宿主会把 `messages` 当作真正的 `user` / `assistant` 历史消息参与统一提示词组装，而不是把它们塞进一条说明文字里。",
  "",
  "`messages` 是 APP 自己的私有多轮历史；短期记忆事件流由宿主单独读取，里面包含该角色最近的聊天、群聊、其他 APP 事件、日记、朋友圈等。最终进入提示词时，宿主会把短期记忆事件流和 `messages` 按 `createdAt` / `timestamp` 合并排序，再放进 `<shortTermMemory>`。因此，多轮 APP 保存历史时应保留每条消息的 `createdAt`。",
  "",
  "```js",
  "const scene = await AiPhone.db.get(\"scenes\", sceneId);",
  "const turns = scene.turns || [];",
  "",
  "const result = await AiPhone.ai.generate({",
  "  characterId: selectedCharacterId,",
  "  appTags: [\"infinite_flow\", \"scene\"],",
  "  messages: turns.slice(-24).map(turn => ({",
  "    role: turn.role,",
  "    content: turn.content,",
  "    createdAt: turn.createdAt",
  "  })),",
  "  instruction: `",
  "当前副本摘要：",
  "${scene.summary || \"暂无\"}",
  "",
  "当前场景状态：",
  "${JSON.stringify(scene.state || {}, null, 2)}",
  "",
  "用户本轮行动：",
  "${userAction}",
  "",
  "请作为当前角色继续推进剧情，只输出角色这一轮的回复。",
  "`",
  "});",
  "console.log(result.text);",
  "",
  "await AiPhone.db.update(\"scenes\", sceneId, {",
  "  turns: [",
  "    ...turns,",
  "    { role: \"user\", content: userAction, createdAt: new Date().toISOString() },",
  "    ...result.appendMessages",
  "  ]",
  "});",
  "```",
  "",
  "* `messages` / `appMessages`：APP 自己维护的多轮记录，支持 `role: \"user\" | \"assistant\" | \"system\" | \"tool\"`、`content`、`createdAt`，也支持 `mediaType`、`rawResponseText`、`nativeToolCalls`、`nativeToolResult` 等工具上下文字段。不传时表示本 APP 没有私有多轮历史；宿主仍会通过短期记忆事件流补入该角色最近发生的聊天和其他 APP 事件。",
  "* 消息可带 `image`（`data:image/...` 的 dataURL）走视觉通道让角色\"看到\"图片：单次生成最多 4 张、单张 dataURL 不超过 2MB，建议传压缩过的缩略图。用户模型不支持或关闭图像识别时自动降级为 `[图片]` 文本，APP 无需判断——但提示词里应写明\"看不到图片内容时不要臆测细节\"。",
  "* `instruction`：本轮任务说明，适合放当前状态、用户本轮操作、输出要求。不要把几十轮历史都拼进 `instruction`；多轮历史应放 `messages`。",
  "* `result.text`：本轮工具循环结束后的最终可显示回复文本。",
  "* `result.appendMessages`：本轮生成新增的上下文消息，包含中间工具调用、工具结果和最终 assistant 回复。剧情 APP 应把它们追加到自己的多轮记录里；下一轮再作为 `messages` 原样传回。文本协议工具结果会以 `role: \"user\"` + `mediaType: \"tool_result\"` 保存；原生工具结果会以 `role: \"tool\"` + `nativeToolResult` 保存。",
  "* `historyLimit`：可选；当生成方案使用 `history: \"recent\"` 时，限制 `messages` / `appMessages` 只取最近多少条。通常由 APP 自己决定传多少轮历史。",
  "",
  "**多角色生成**：把 `characterId` 换成 `characterIds` 数组（或传一个已有群聊的 `sessionId`），一次生成里同台多位角色。心智模型和单角色完全一致：宿主组装\"多人资料包\"（每位角色的完整人设、状态、记忆、日程、世界书都进入上下文），场景任务由你的 `presets.json` 条目按 `appTags` 命中——宿主不会混入自己内置的聊天/群聊格式条目。**输出格式完全由你的场景条目约定，返回原始文本，由 APP 自行解析渲染**（想要谁说哪句，就在预设里规定台词标记格式）。",
  "",
  "```js",
  "const result = await AiPhone.ai.generate({",
  "  characterIds: [\"char_a\", \"char_b\", \"char_c\"],",
  "  appTags: [\"theater\", \"scene\"],",
  "  instruction: \"三人在天台对峙，按剧本推进这一幕，每人至少发言一次。\"",
  "});",
  "// result.text 是模型原始输出，按你在预设里约定的格式自行解析",
  "const lines = result.text.match(/\\[台词@[^\\]]+\\]/g);",
  "```",
  "",
  "* `characterIds`：参与生成的角色 id 数组。也可以改传 `sessionId`（已存在的群聊会话），此时自动带入该群最近的聊天记录作为上下文。",
  "* `result.text`：模型的原始输出文本，宿主不做任何按角色切分或格式清洗。",
  "* `result.appendMessages`：与单角色模式相同，用于多轮续写时作为 `messages` 传回。",
  "* 多角色模式同样支持 `messages`、`instruction`、`appTags`、`historyLimit` 和生成方案；暂不支持工具调用。",
  "",
  "需 `ai.generate`。",
  "",
  "不需要角色聊天链路、只想调用通用模型时，用 `ai.chat` / `ai.embed` / `ai.classify`：",
  "",
  "```js",
  "const chat = await AiPhone.ai.chat({",
  "  messages: [",
  "    { role: \"system\", content: \"你是简短分类助手。\" },",
  "    { role: \"user\", content: \"这条评论看起来像差评吗？\" }",
  "  ],",
  "  timeoutMs: 60000",
  "});",
  "const embedding = await AiPhone.ai.embed({ text: \"冬阴功汤很好喝\" });",
  "const cls = await AiPhone.ai.classify({ text: \"太辣了\", labels: [\"好评\", \"中评\", \"差评\"] });",
  "```",
  "",
  "`ai.chat` 的 `timeoutMs` 可选，不传时宿主不主动截断；传入后只影响本次请求。分别需 `ai.chat` / `ai.embed` / `ai.classify`。",
  "",
  "需要一张配图时用 `ai.generateImage`，它会复用用户在宿主设置里配置好的生图 API（APP 自己不需要管理生图 API Key）：",
  "",
  "```js",
  "const image = await AiPhone.ai.generateImage({",
  "  prompt: \"一张温暖的深夜街角便利店插画，暖黄灯光，雨后地面反光\",",
  "  characterId: selectedCharacterId,",
  "  useReferenceImage: true",
  "});",
  "if (image.dataUrl) imgEl.src = image.dataUrl;",
  "```",
  "",
  "* `prompt`：生图描述，必填。`characterId` + `useReferenceImage: true` 时会带上该角色在宿主设置里配置的参考图，让画面里的人物更贴近角色形象；不传 `useReferenceImage` 或角色没配参考图则按纯文字描述生成。",
  "* 返回 `{ ok, dataUrl, mimeType, prompt, revisedPrompt?, usedReferenceImage }`，`dataUrl` 可直接用于 `<img src>`。",
  "* **要长期保存生成的图片时，用 `media.put` 换成引用再存 db**（见 5.10），不要把 `dataUrl` 原样塞进 `db.create/update`——几张图就是几 MB，会把存档拖得又慢又容易崩。",
  "* 用户没有在宿主设置里配置/启用生图 API 时会抛错，请 `try/catch` 并提示用户先去设置里配置，不要假设一定能生图成功。",
  "* 生图通常比文本生成慢（10~30 秒常见），请在 UI 上做等待态；需要更长上限时可传 `timeoutMs`。",
  "* 需 `ai.generateImage`。",
  "",
  "### 5.9 语音能力",
  "",
  "```js",
  "const voices = await AiPhone.voice.readProfiles({ characterId: selectedCharacterId });",
  "const speech = await AiPhone.voice.tts({ characterId: selectedCharacterId, text: \"你的外卖到了。\" });",
  "// 播放必须走宿主代播,不要自己 new Audio() 或用 Web Audio(原因见下)",
  "await AiPhone.voice.play({ dataUrl: speech.dataUrl });  // 播完才 resolve",
  "const stt = await AiPhone.voice.stt({ lang: \"zh-CN\", timeoutMs: 15000 });",
  "// 录一段真人语音(拿到音频本身,不是文字)。APP 的 iframe 没有麦克风权限,",
  "// 所以录音在宿主页进行,录完把 dataUrl 交回来。",
  "const clip = await AiPhone.voice.record({ maxMs: 15000 });   // → { ok, dataUrl, mimeType, size, ms }",
  "await AiPhone.voice.stopRecord();                            // 提前收音(例如「松开发送」)",
  "",
  "const pickedAudio = await AiPhone.media.pick({ accept: \"audio/*\" });",
  "const cloned = await AiPhone.voice.clone({",
  "  voiceConfigId: voices.selected?.id,",
  "  voiceId: \"waimai_voice_001\",",
  "  name: \"外卖提示音\",",
  "  audioDataUrl: pickedAudio.file.dataUrl",
  "});",
  "```",
  "",
  "`readProfiles`/`tts`/`stt`/`clone` 分别需 `voice.readProfiles`/`voice.tts`/`voice.stt`/`voice.clone`；`record`/`stopRecord` 沿用 `voice.stt` 权限(同样是采集麦克风)。`record` 与 `stt` 互不干扰,可并行——识别拿文字喂 AI,录音拿音频给人听。同一时刻只允许一个录音,重复调用会 reject。上例 `clone` 用了 `media.pick` 选音频，所以也需 `media.pick`。`clone` 当前接入 Minimax 克隆接口。",
  "",
  "**播放一律用 `voice.play`(宿主代播),不要在 APP 里自己建 `<audio>` 或 Web Audio**：APP 跑在沙盒 iframe 里，自建 `<audio>` 会让 iOS 锁屏媒体卡片绑定到打不开的空白地址（用户一点整个应用就白屏）；Web Audio 则会被 iOS 静音拨键整个静音。`voice.play` 由宿主页面的媒体元素播放，两个坑都没有。",
  "",
  "```js",
  "await AiPhone.voice.play({ dataUrl: speech.dataUrl });            // 主通道,播完 resolve",
  "AiPhone.voice.play({ channel: \"ambience\", dataUrl: bgmDataUrl, loop: true, volume: 0.3 }); // 循环环境音",
  "await AiPhone.voice.stopPlayback({ channel: \"voice\" });          // 停止",
  "await AiPhone.voice.pausePlayback({});                             // 暂停(默认 voice 通道)",
  "await AiPhone.voice.resumePlayback({});                            // 继续",
  "```",
  "",
  "* 两个通道：`voice`（默认，台词/提示音）和 `ambience`（循环背景音），互不打断；同通道新的播放会顶掉旧的。",
  "* `dataUrl` 也可以换成 `media.put` 返回的 `media-store://` 引用（推荐，见 5.10），此时音频数据完全不经过通信桥。",
  "* 播放需 `voice.tts` 权限。播放被浏览器拦截时会 reject，请 `try/catch` 做文字兜底。",
  "",
  "`voice.tts` 可选传 `emotion`（Minimax 专属，取值 `happy`/`sad`/`angry`/`fearful`/`disgusted`/`surprised`/`calm`/`neutral`/`fluent`，非法值会被忽略）来控制整句情绪。语音是否支持这个字段、是否支持更进一步的插入语标签（如 `(laughs)` `(sighs)` `(breath)`，这个仅 Minimax `speech-2.8-hd`/`speech-2.8-turbo` 支持，其它模型/供应商遇到会被当英文原样朗读），请先用 `voice.readProfiles` 读出 `selected.provider`/`selected.model` 自行判断，不要无条件假设所有语音配置都支持。",
  "",
  "**返回结构**：",
  "",
  "* `voice.tts` → `{ ok, configId, provider, voiceId, mimeType, size, dataUrl }`，`dataUrl` 可直接播放。",
  "* `voice.stt` → `{ ok, text, interim?, reason? }`。",
  "* `voice.readProfiles` → `{ selected, profiles, characterId? }`，每个 profile 含 `provider`/`model`，可用于判断当前语音支持的高级能力。",
  "",
  "### 5.10 日程、世界书和媒体",
  "",
  "```js",
  "const week = await AiPhone.calendar.read({ ownerType: \"character\", ownerId: selectedCharacterId });",
  "await AiPhone.calendar.create({",
  "  ownerType: \"character\", ownerId: selectedCharacterId,",
  "  date: \"2026-06-25\", startTime: \"18:30\", endTime: \"19:00\",",
  "  title: \"等外卖\", location: \"家\"",
  "});",
  "",
  "const world = await AiPhone.world.list({ query: \"大型剧情活动\" });",
  "",
  "const picked = await AiPhone.media.pick({ accept: \"image/*\" });",
  "const saved = await AiPhone.media.save({ dataUrl: picked.file.dataUrl, type: \"custom_app_media\" });",
  "```",
  "",
  "日程需 `calendar.read`/`calendar.write`；世界书需 `world.read`；媒体需 `media.pick`/`media.save`。",
  "",
  "#### 媒体库：大文件的正确存法",
  "",
  "音频、图片这类大文件**不要以 dataURL 形式存进 `db.*` 记录**——db 记录是整体序列化的文本，塞几段配音进去，之后每次小改动都要重新序列化几十 MB，慢、费内存、在 iOS 上还可能把整个应用压崩。正确做法是先 `media.put` 换成引用，db 里只存引用字符串：",
  "",
  "```js",
  "// 存:dataURL → 引用(Blob 落盘,不占内存)",
  "const stored = await AiPhone.media.put({ dataUrl: speech.dataUrl });",
  "await AiPhone.db.create(\"clips\", { title: \"晚安\", audioRef: stored.ref });",
  "",
  "// 播:引用直接交给宿主代播,音频数据不经过通信桥",
  "await AiPhone.voice.play({ dataUrl: clip.audioRef });",
  "",
  "// 显示图片:引用换回 dataURL(blob objectURL 在沙盒 iframe 里会被同源规则拒载,不要用)",
  "const img = await AiPhone.media.get({ ref: item.coverRef });",
  "coverEl.src = img.dataUrl;",
  "",
  "// 删:记录删除时把引用的媒体一并删掉,不留垃圾",
  "await AiPhone.media.delete({ ref: item.coverRef });",
  "```",
  "",
  "* `media.put({ dataUrl })` → `{ ref, mime, category }`，`ref` 形如 `media-store://...`；单件上限 25MB。需 `app.data.write`。",
  "* `media.get({ ref })` → `{ ref, mime, dataUrl }`，dataURL 可直接用于 `<img src>`/CSS 背景/导出。需 `app.data.read`。只能读取本 APP 存入的媒体。按需取、别整库预加载，显示中的图片才占内存。",
  "* `media.delete({ ref })` 删除媒体本体；删除 db 记录时记得同步删除它引用的媒体。卸载 APP 清数据时宿主会自动清理全部媒体。",
  "",
  "**日程字段**：",
  "",
  "* `calendar.read({ ownerType, ownerId/characterId, weekStart/date, includeAll })` → `{ ownerType, ownerId, weekStart, plan, plans? }`，`plan.items` 是本周日程数组。",
  "* `calendar.create/update/write` 写单个日程必填 `date`、`startTime`、`endTime`、`title`。`date` 为 `YYYY-MM-DD`，`startTime`/`endTime` 为 `HH:MM`。可选 `id`、`location`、`source`。",
  "* `calendar.write({ operation: \"replace\", items: [...] })` 替换整周；`operation: \"delete\"` 时传 `itemId` 或 `id`。",
  "",
  "**世界书字段**：",
  "",
  "* `world.list({ query, includeEntries })` → `{ books: [...] }`；`world.get(id)` 或 `world.read({ id })` → `{ book }`。",
  "* world book 常用字段：`id`、`name`、`description`、`entries`、`entryCount`、`createdAt`、`updatedAt`。",
  "* entry 常用字段：`key`、`content`、`comment`。",
  "* 世界书对 APP 是只读的：角色绑定的世界书会自动进入 `ai.generate` 生成链路，APP 无需干预；APP 自己的场景背景写进 `presets.json` 条目即可。",
  "",
  "### 5.10.1 定位（宿主代理）",
  "",
  "APP 沙盒 iframe 是不透明源，`navigator.geolocation` 永远拿不到权限，所以定位由宿主页面代理（与 `voice.play` 同理）。坐标为 WGS-84；要在高德等国内地图上显示需 APP 自行转 GCJ-02。",
  "",
  "```js",
  "// 单次定位（需 geo.read）",
  "const pos = await AiPhone.geo.get({ timeoutMs: 10000 });",
  "console.log(pos.lat, pos.lng, pos.accuracy);",
  "",
  "// 持续定位（需 geo.watch；事件需在 manifest extensions.events 声明 geo.position / geo.error）",
  "AiPhone.on(\"geo.position\", p => updateMyDot(p.lat, p.lng));",
  "AiPhone.on(\"geo.error\", e => console.warn(e.message));",
  "await AiPhone.geo.watch({});",
  "// 不用时务必停掉：",
  "await AiPhone.geo.clearWatch();",
  "```",
  "",
  "首次调用会触发浏览器的位置授权弹窗；用户拒绝时 `geo.get` reject、watch 走 `geo.error` 事件，APP 要准备好降级（手动选点等）。持续定位仅在 APP 打开期间有效，运行器关闭时宿主会自动停止监听。",
  "",
  "### 5.11 注册和调用 APP 工具",
  "",
  "小手机有一套统一的聊天工具箱，位置在“设置 → 聊天工具箱”。工具箱用于让角色在聊天或 APP 生成过程中执行真实动作，例如调用外部 REST API、调用 MCP 服务、执行组合工具、调用小手机内部能力，或和小手机里的其他 APP 联动。比如音乐工具可以让角色在聊天里控制音乐 APP；自定义外卖 APP 也可以注册“点外卖”“提交外卖评价”等工具给角色调用。",
  "",
  "工具不是“换一种写提示词”。如果角色只需要生成一句话、润色内容、判断情绪、写评论草稿，优先用预设条目和 `AiPhone.ai.generate`，不要声明工具。工具只用于需要读写状态、调用接口、创建订单、提交评价、控制其他 APP 这类真实动作的场景。",
  "",
  "工具箱采用二级懒加载：",
  "",
  "* 单个工具会直接暴露给角色。",
  "* 多个工具会先暴露成一个“工具套件/元工具”，角色需要时先展开这个套件，再调用里面的具体子工具。",
  "* REST 工具套件、组合工具套件、MCP 服务、自定义 APP 的多工具声明都会走这套逻辑。",
  "* 这样可以避免一次性把大量工具 schema 塞进提示词，角色只在需要时获取具体动作说明。",
  "",
  "自定义 APP 接入工具箱的方式是：在 manifest 的 `extensions.tools` 里声明一组 APP 工具。安装 APP 后，`visibility: \"shared\"` 的工具会成为聊天工具箱的一部分；卸载 APP 后随 APP 移除。一个 APP 只声明 1 个共享工具时，它会作为单工具出现；同一个 APP 声明多个共享工具时，会作为“该 APP 的工具套件”出现，展开后再看到子工具。`visibility: \"private\"` 的工具只给本 APP 内部使用，不显示在聊天工具箱里。",
  "",
  "是否让角色看到 APP 工具，由权限、`visibility` 和 `{{tools}}` 共同决定：",
  "",
  "* `permissions` 需要包含 `chat.tools`。",
  "* `visibility: \"private\"`：只有所属 APP 自己的 `AiPhone.ai.generate` 链路能看到这个工具。",
  "* `visibility: \"shared\"`：所属 APP、普通聊天和其他 APP 的生成链路都能看到这个工具；也会显示在“设置 → 聊天工具箱”里，用户可以统一开启或关闭。",
  "* 当前生成链路的预设条目里必须有 `{{tools}}`，工具才会交给模型。没有 `{{tools}}` 时，即使 manifest 声明了工具，模型也不会看到工具说明或原生工具 schema。",
  "",
  "工具执行时，宿主会优先复用已打开 APP 的 handler；如果 APP 没打开，会临时启动隐藏运行环境，等待 APP 调用 `AiPhone.tools.handle(handlerName, fn)` 注册同名 handler，然后把工具参数交给它执行。handler 里的异步读写、网络请求、聊天写入等操作要 `await` 或返回 Promise，否则隐藏运行环境可能会提前结束。隐藏运行环境默认最多保留 5 分钟；确实需要更久时，可在工具声明里写 `timeoutMs`，最高 30 分钟。`actions` / `resultTemplate` 可以作为非常简单工具的声明式兜底，但不是必须路径；需要读写 APP 私有数据、提交订单、写评价这类真实逻辑时，优先写 handler。",
  "",
  "manifest 里声明一组工具：",
  "",
  "```json",
  "{",
  "  \"permissions\": [\"chat.tools\", \"app.data.write\"],",
  "  \"extensions\": {",
  "    \"tools\": [",
  "      {",
  "        \"id\": \"submit-takeout-review\",",
  "        \"name\": \"提交外卖评价\",",
  "        \"description\": \"把已完成外卖订单的评价写入外卖 APP 的店铺评价区。只有需要真正提交评价时才调用。\",",
  "        \"visibility\": \"shared\",",
  "        \"handler\": \"submitTakeoutReview\",",
  "        \"parameterSchema\": {",
  "          \"type\": \"object\",",
  "          \"properties\": {",
  "            \"orderId\": { \"type\": \"string\", \"description\": \"订单 ID\" },",
  "            \"rating\": { \"type\": \"number\", \"description\": \"1 到 5 星评分\" },",
  "            \"comment\": { \"type\": \"string\", \"description\": \"角色写下的评价内容\" }",
  "          },",
  "          \"required\": [\"orderId\", \"rating\", \"comment\"]",
  "        }",
  "      }",
  "    ]",
  "  }",
  "}",
  "```",
  "",
  "APP 代码加载时注册 handler：",
  "",
  "```js",
  "AiPhone.tools.handle(\"submitTakeoutReview\", async (args, context) => {",
  "  const review = await AiPhone.db.create(\"reviews\", {",
  "    orderId: args.orderId,",
  "    rating: args.rating,",
  "    comment: args.comment,",
  "    characterId: context.characterId || \"\",",
  "    createdAt: new Date().toISOString()",
  "  });",
  "",
  "  return {",
  "    success: true,",
  "    data: {",
  "      reviewId: review.id,",
  "      orderId: args.orderId,",
  "      rating: args.rating,",
  "      comment: args.comment",
  "    },",
  "    userNotice: \"外卖评价已提交\"",
  "  };",
  "});",
  "```",
  "",
  "handler 的返回值会作为工具结果进入本轮生成上下文。不要在 handler 里额外写入聊天历史，除非这个工具的目的就是向聊天室发送一条可见消息或卡片。",
  "",
  "APP 内部也可以直接调用当前 APP 可见的工具。这里是 APP 代码主动调用工具，不经过角色思考：",
  "",
  "```js",
  "const result = await AiPhone.tools.invoke(\"提交外卖评价\", {",
  "  orderId: \"order_123\",",
  "  rating: 5,",
  "  comment: \"味道很好，包装也很仔细。\"",
  "});",
  "```",
  "",
  "让某个 APP 生成场景允许角色调用工具：在 `presets.json` 加一条能被本次 `appTags` 匹配到的 `{{tools}}` 条目。只有这条预设进入提示词后，角色才会看到工具箱。",
  "",
  "```json",
  "[",
  "  {",
  "    \"id\": \"waimai-review-tools\",",
  "    \"name\": \"外卖评价工具\",",
  "    \"role\": \"system\",",
  "    \"content\": \"{{tools}}\",",
  "    \"tags\": [\"waimai\", \"review\"],",
  "    \"enabled\": true",
  "  }",
  "]",
  "```",
  "",
  "```js",
  "const result = await AiPhone.ai.generate({",
  "  characterId: selectedCharacterId,",
  "  appTags: [\"waimai\", \"review\"],",
  "  instruction: \"请根据最近的订单和聊天语境，决定是否需要提交一条外卖评价。\"",
  "});",
  "```",
  "",
  "工具名、描述、参数 schema 来自 manifest `extensions.tools`。绑定的 API 使用文本协议工具时，`{{tools}}` 会展开成工具说明；使用原生工具时，`{{tools}}` 不展开文本说明，真实工具 schema 会按 API 的原生格式随请求传入。如果只是让角色写一段评价文本，不需要工具；只有需要把评价真正写入外卖 APP 数据时，才调用工具。",
  "",
  "### 5.12 向聊天室发送 APP 卡片",
  "",
  "```js",
  "const [character, userProfile] = await Promise.all([",
  "  AiPhone.characters.get(selectedCharacterId),",
  "  AiPhone.user.getProfile({ characterId: selectedCharacterId })",
  "]);",
  "const characterName = character?.name || \"对方\";",
  "const userName = userProfile?.name || \"你\";",
  "",
  "await AiPhone.chat.sendCard({",
  "  characterId: selectedCharacterId,",
  "  role: \"user\",",
  "  summary: `${userName}给${characterName}点了一份外卖：冬阴功汤、椰汁饭，预计 35 分钟送达。`,",
  "  historyText: `[外卖：${userName}给${characterName}点了一份外卖；餐品：冬阴功汤、椰汁饭；预计 35 分钟送达。]`,",
  "  historyRole: \"user\",",
  "  card: {",
  "    appLabel: \"Float 外卖\",",
  "    title: \"订单已提交\",",
  "    subtitle: \"ORDER CARD\",",
  "    status: \"配送中\",",
  "    accentColor: \"#f97316\",",
  "    sections: [",
  "      { title: \"餐品\", rows: [",
  "        { label: \"冬阴功汤\", value: \"x1 · ¥38\" },",
  "        { label: \"椰汁饭\", value: \"x1 · ¥12\" }",
  "      ] },",
  "      { title: \"配送\", rows: [",
  "        { label: \"收餐人\", value: characterName },",
  "        { label: \"预计送达\", value: \"35 分钟\" },",
  "        { label: \"订单号\", value: \"W-1028\" }",
  "      ] }",
  "    ],",
  "    actions: [{ label: \"查看订单\" }]",
  "  }",
  "});",
  "```",
  "",
  "`role` 控制卡片在聊天室里的显示位置，可为 `user`/`assistant`/`system`；`card` 控制用户看到的卡片布局，建议像购物 APP 的送礼卡片一样使用状态、编号、来源、明细等结构化字段；`historyText` 是 AI 可见聊天历史文本，不填时用 `summary`/`card.body`。写入历史时优先使用真实显示名，上例通过 `characters.get` 和 `user.getProfile` 取到角色名、用户昵称后再拼接，避免 AI 在后续剧情里看到\"用户\"、\"角色\"这类占位词。`historyRole` 控制 `historyText` 进入 AI 历史时的角色，不填时跟随 `role`。例如角色主动发出的卡片可以 `role: \"assistant\"`、`historyRole: \"system\"`，让 UI 看起来像角色发卡片，但提示词里只作为事实记录。需 `chat.sendCard`、`characters.read`、`user.profile.read`。",
  "",
  "> `card.actions` 只负责显示按钮。用户点卡片或按钮会打开 APP；真正的确认、扣款、写数据由 APP 内页面完成。完成后如果要把原卡片从\"待确认\"改成\"已确认\"，用 `AiPhone.chat.updateCard`。",
  "",
  "从聊天卡片打开 APP 时，`launchContext` 会带 `messageId` 和 `sessionId`。确认完成后可更新原卡片：",
  "",
  "```js",
  "const launchContext = await AiPhone.app.getLaunchContext();",
  "await AiPhone.chat.updateCard({",
  "  messageId: launchContext.messageId,",
  "  sessionId: launchContext.sessionId,",
  "  status: \"已确认\",",
  "  openDisabled: true,",
  "  actions: [{ label: \"已确认\", style: \"muted\", disabled: true }]",
  "});",
  "```",
  "",
  "**卡片不是固定模板**。上面的 `card` 结构由宿主渲染；如果需要完全不同的外观，可传**静态 HTML 卡片**。宿主用 sandbox iframe 展示、不执行脚本：",
  "",
  "```js",
  "const [character, userProfile] = await Promise.all([",
  "  AiPhone.characters.get(selectedCharacterId),",
  "  AiPhone.user.getProfile({ characterId: selectedCharacterId })",
  "]);",
  "const characterName = character?.name || \"对方\";",
  "const userName = userProfile?.name || \"你\";",
  "",
  "await AiPhone.chat.sendCard({",
  "  characterId: selectedCharacterId, role: \"user\",",
  "  summary: `${userName}给${characterName}点的外卖小票：冬阴功汤、椰汁饭，预计 35 分钟送达。`,",
  "  historyText: `[外卖：${userName}给${characterName}点了一份外卖小票；餐品：冬阴功汤、椰汁饭；预计 35 分钟送达。]`,",
  "  card: {",
  "    height: 260,",
  "    html: `",
  "      <style>",
  "        .receipt { min-height:260px; padding:18px; color:#2f241c;",
  "          background:#fffaf0; border:1px solid rgba(95,62,35,.16);",
  "          font:14px/1.7 -apple-system,BlinkMacSystemFont,sans-serif; }",
  "        .total { margin-top:12px; border-top:1px dashed #c9a36a; padding-top:10px; font-weight:700; }",
  "      </style>",
  "      <div class=\"receipt\">",
  "        <h3>Float 外卖小票</h3>",
  "        <p>冬阴功汤 x1 · ¥38</p>",
  "        <p>椰汁饭 x1 · ¥12</p>",
  "        <p class=\"total\">预计 35 分钟送达</p>",
  "      </div>`",
  "  }",
  "});",
  "```",
  "",
  "> HTML 卡片只负责展示。要改变状态、扣款、通知、让角色回复，仍用对应 SDK 接口。",
  "",
  "### 5.13 让聊天感知 APP 事件",
  "",
  "只想让角色知道发生过某件事、不需要卡片时，用 `chat.writeHistory`：",
  "",
  "```js",
  "const userProfile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const userName = userProfile?.name || \"你\";",
  "",
  "await AiPhone.chat.writeHistory({",
  "  characterId: selectedCharacterId, role: \"user\",",
  "  content: `[打卡：${userName}完成了今天的晨间打卡，状态是精神不错。]`",
  "});",
  "```",
  "",
  "需 `chat.write` 或 `chat.sendMessage`；如果像上例一样读取用户昵称，还需 `user.profile.read`。",
  "",
  "> 自定义 APP **不开放**系统指令/静默上下文注入。要让 AI 看见事件，请写入普通历史消息，或发送带 `historyText` 的 APP 卡片。",
  "",
  "### 5.14 请求角色在聊天室回复",
  "",
  "推荐流程：先用 `chat.writeHistory` 或 `chat.sendCard` 把 APP 事件写进真实聊天历史，再请求角色按普通聊天链路回复。",
  "",
  "```js",
  "const userProfile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const userName = userProfile?.name || \"你\";",
  "",
  "await AiPhone.chat.writeHistory({",
  "  characterId: selectedCharacterId,",
  "  role: \"user\",",
  "  content: `[打卡：${userName}完成了今天的晨间打卡，状态是精神不错。]`",
  "});",
  "",
  "await AiPhone.chat.requestReply({",
  "  characterId: selectedCharacterId",
  "});",
  "```",
  "",
  "需 `chat.requestReply`。`requestReply` 触发的是普通聊天室回复，和用户在聊天框发消息后的生成链路一致；它不接收 APP 场景 tags，也不会加载 APP 专属预设。角色能看到的是你刚刚写入的历史消息或卡片 `historyText`。如果像上例一样读取用户昵称，还需 `user.profile.read`。",
  "",
  "如果 APP 需要用自己的 APP 预设生成内容，请调用 `AiPhone.ai.generate`，然后用 `chat.writeHistory` 或 `chat.sendCard` 把结果写回聊天。",
  "",
  "### 5.15 打开角色聊天室",
  "",
  "```js",
  "await AiPhone.chat.openConversation({ characterId: selectedCharacterId });",
  "```",
  "",
  "### 5.16 修改聊天联系人状态",
  "",
  "可做拉黑、免打扰这类和聊天联动的 APP：",
  "",
  "```js",
  "await AiPhone.chat.setContactState({",
  "  characterId: selectedCharacterId, isBlacklisted: true, isMuted: true",
  "});",
  "await AiPhone.chat.unblock(selectedCharacterId);",
  "await AiPhone.chat.unmute(selectedCharacterId);",
  "```",
  "",
  "需 `chat.contacts.write`。",
  "",
  "### 5.17 读取聊天历史",
  "",
  "```js",
  "const current = await AiPhone.chat.getCurrentSession();",
  "const history = await AiPhone.chat.readHistory({ sessionId: current?.sessionId, limit: 30 });",
  "```",
  "",
  "需 `chat.read`。`getCurrentSession` **只有从聊天卡片 / + 号面板进入时**才返回会话信息，桌面直接打开时为 `null`。所以不要默认能拿到当前会话——桌面入口下，`sessionId`/`characterId` 应由用户在 APP 内自己选择（如先用 `characters.list` 让用户挑角色）。",
  "",
  "### 5.18 监听聊天事件",
  "",
  "可监听 manifest `extensions.events` 里声明过的事件。当前支持 `chat.message.created`（响应用户或角色的新消息）和 `bridge.data`（现实桥数据广播，见 5.25）。事件声明里写 `background: true` 时，即使 APP 没打开，宿主也会临时启动隐藏运行环境，执行同一段 `AiPhone.on` handler，执行完成后销毁；隐藏运行环境默认最多保留 5 分钟，确实需要更久时可在事件声明里写 `timeoutMs`，最高 30 分钟。",
  "",
  "```js",
  "const stop = AiPhone.on(\"chat.message.created\", async (payload) => {",
  "  const text = payload.message?.content || \"\";",
  "  if (payload.message?.role !== \"assistant\") return;",
  "  if (!text.includes(\"[漂流瓶:\")) return;",
  "",
  "  await AiPhone.db.create(\"bottles\", {",
  "    content: text,",
  "    characterId: payload.characterId,",
  "    messageId: payload.message.id,",
  "    createdAt: new Date().toISOString()",
  "  });",
  "});",
  "// 不再需要时：",
  "stop();",
  "```",
  "",
  "需在 `extensions.events` 声明该事件，并声明 `chat.read` 或 `chat.read.background` 权限。后台 handler 里的异步操作要 `await` 或返回 Promise，宿主会等待 Promise 完成；如果只启动异步任务但不返回 Promise，隐藏运行环境可能会提前销毁。后台 handler 写出的聊天消息会带 `custom_app_background` 来源，宿主不会再用这些消息触发后台监听，避免无限循环。",
  "",
  "### 5.19 读取记忆",
  "",
  "```js",
  "const core = await AiPhone.memory.readCore({ characterId: selectedCharacterId });",
  "const longTerm = await AiPhone.memory.readLongTerm({ characterId: selectedCharacterId, query: \"清淡口味\" });",
  "const shortTerm = await AiPhone.memory.readShortTerm({ characterId: selectedCharacterId, limit: 30 });",
  "const found = await AiPhone.memory.search({ characterId: selectedCharacterId, query: \"喜欢少辣\" });",
  "```",
  "",
  "分别需 `memory.readCore` / `memory.readLongTerm` / `memory.readShortTerm` / `memory.search`。",
  "",
  "### 5.20 写入记忆",
  "",
  "三种写法，按\"重要程度\"选：",
  "",
  "**`memory.add`** —— 写长期/核心记忆，**只在确实重要、未来需长期影响角色时用**。不要把每次点击都写成长期记忆。",
  "",
  "```js",
  "const userProfile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const userName = userProfile?.name || \"你\";",
  "",
  "await AiPhone.memory.add({",
  "  characterId: selectedCharacterId, type: \"long_term\",",
  "  content: `${userName}长期偏好清淡少辣的食物。`,",
  "  importance: 0.6, reason: \"外卖 APP 多次点单观察\"",
  "});",
  "```",
  "",
  "需 `memory.write`；如果像上例一样读取用户昵称，还需 `user.profile.read`。",
  "",
  "**`memory.suggest`** —— 只是建议写入、需用户或宿主之后确认，**不直接写进长期记忆**。",
  "",
  "```js",
  "const userProfile = await AiPhone.user.getProfile({ characterId: selectedCharacterId });",
  "const userName = userProfile?.name || \"你\";",
  "",
  "await AiPhone.memory.suggest({",
  "  characterId: selectedCharacterId, type: \"long_term\",",
  "  content: `${userName}喜欢清淡少辣的外卖。`, reason: \"多次点单观察\"",
  "});",
  "```",
  "",
  "需 `memory.suggest`；如果像上例一样读取用户昵称，还需 `user.profile.read`。",
  "",
  "**`memory.addTimeline`** —— 将自定义 APP 的事件写入该角色的全局短期记忆事件流。写入后，这条事件会被同一角色下的所有 APP 在 `AiPhone.ai.generate` 的短期记忆事件流里读到。",
  "",
  "注意：`chat.sendCard({ historyText })` 和 `chat.writeHistory` 作为聊天室历史的一部分，也会进入短期记忆事件流。因此，如果已经使用 `chat.sendCard` 或 `chat.writeHistory` 写入同一事件，就无需再重复调用 `memory.addTimeline`。",
  "",
  "```js",
  "const [character, userProfile] = await Promise.all([",
  "  AiPhone.characters.get(selectedCharacterId),",
  "  AiPhone.user.getProfile({ characterId: selectedCharacterId })",
  "]);",
  "const characterName = character?.name || \"对方\";",
  "const userName = userProfile?.name || \"你\";",
  "",
  "const timeline = await AiPhone.memory.addTimeline({",
  "  characterId: selectedCharacterId, appLabel: \"Float 外卖\",",
  "  detail: \"order_delivered\", summary: `${userName}给${characterName}点的冬阴功汤和椰汁饭已经送达。`,",
  "  appEventId: \"order_001\",",
  "  data: { orderId: \"order_001\" }",
  "});",
  "```",
  "",
  "如果这件事后来被撤销、订单取消，或用户删除了对应卡片，可以按同一个 `appEventId` 删除短期时间线；如果只想删某一条，也可以用 `addTimeline` 返回的 `entry.id`：",
  "",
  "```js",
  "await AiPhone.memory.deleteTimeline({",
  "  characterId: selectedCharacterId,",
  "  appEventId: \"order_001\"",
  "});",
  "",
  "await AiPhone.memory.deleteTimeline({ entryId: timeline.entry.id });",
  "```",
  "",
  "`addTimeline` / `deleteTimeline` 都需 `memory.write`；如果像上例一样读取角色名和用户昵称，还需 `characters.read`、`user.profile.read`。",
  "",
  "### 5.21 UI 提示",
  "",
  "```js",
  "await AiPhone.ui.toast(\"已保存\");",
  "await AiPhone.ui.showNotification({ title: \"Float 外卖\", body: \"订单状态已更新。\" });",
  "const ok = await AiPhone.ui.confirm({ title: \"确认删除？\", message: \"删除后不可恢复。\" });",
  "```",
  "",
  "`toast` 需 `ui.toast`，`showNotification` 需 `ui.notification`，`confirm` 无需特殊权限。",
  "",
  "### 5.22 通知和桌面红点",
  "",
  "```js",
  "await AiPhone.notifications.create({",
  "  title: \"外卖已送达\", body: \"冬阴功汤和椰汁饭已经送到门口。\",",
  "  badgeDelta: 1, data: { orderId: \"order_001\" }",
  "});",
  "const badge = await AiPhone.notifications.getBadge();",
  "await AiPhone.notifications.setBadge(badge + 1);",
  "await AiPhone.notifications.clearBadge();",
  "const notices = await AiPhone.notifications.list({ unreadOnly: true });",
  "await AiPhone.notifications.markAllRead();",
  "```",
  "",
  "需 `notifications.read` / `notifications.write`。",
  "",
  "### 5.23 后台定时任务",
  "",
  "适合\"外卖预计送达\"\"明天提醒打卡\"这类延迟动作。浏览器关闭时任务不真正运行，但用户重新打开小手机后会**补跑已到期的任务**。",
  "",
  "```js",
  "const [character, userProfile] = await Promise.all([",
  "  AiPhone.characters.get(selectedCharacterId),",
  "  AiPhone.user.getProfile({ characterId: selectedCharacterId })",
  "]);",
  "const characterName = character?.name || \"对方\";",
  "const userName = userProfile?.name || \"你\";",
  "",
  "await AiPhone.tasks.schedule({",
  "  id: \"order_001_delivered\",",
  "  delayMs: 35 * 60 * 1000,",
  "  actions: [",
  "    { type: \"notification\", title: \"外卖到了\", body: \"你的冬阴功汤已经送达。\", badgeDelta: 1 },",
  "    { type: \"chat.card\", characterId: selectedCharacterId,",
  "      role: \"user\", historyRole: \"user\",",
  "      title: \"外卖已送达\", body: \"冬阴功汤、椰汁饭已经送到门口。\",",
  "      historyText: `[外卖：${userName}给${characterName}点的冬阴功汤、椰汁饭已送达]` },",
  "    { type: \"chat.reply\", characterId: selectedCharacterId }",
  "  ]",
  "});",
  "```",
  "",
  "需 `tasks.schedule`，以及动作自身对应权限；如果像上例一样读取角色名和用户昵称，还需 `characters.read`、`user.profile.read`。",
  "",
  "> 后台任务里**每个 action 都是独立动作，不会自动继承外层 `appTags`**。`chat.reply` 只触发普通聊天室回复；如果需要 APP 场景预设，请在任务中先用 APP 自己的 `AiPhone.ai.generate` 生成内容，再写入聊天历史或卡片。",
  "",
  "**可用动作 type**：`notification`、`badge`、`chat.card`、`chat.history`、`chat.message`、`chat.reply`、`memory.add`、`memory.timeline`、`memory.deleteTimeline`、`memory.suggest`、`wallet.pay`、`chat.contact`、`calendar.write`。",
  "",
  "**动作字段速查**：",
  "",
  "|type|字段|",
  "|-|-|",
  "|`notification` / `ui.notification`|`title`、`body`、`badgeDelta`、`data`|",
  "|`badge` / `notifications.badge`|`count` 或 `delta`|",
  "|`chat.card`|`characterId`、`role`、`historyRole`、`title`、`body`、`summary`、`historyText`、`card`|",
  "|`chat.history` / `chat.message`|`characterId`、`role`、`content`|",
  "|`chat.reply`|`characterId`、`context`。`context` 会先写成一条 `user` 历史消息；如果前一步已经用 `chat.card` 或 `chat.history` 写过事件，就不要再传 `context`|",
  "|`memory.add`|`characterId`、`content`、`type`、`importance`、`reason`|",
  "|`memory.timeline` / `memory.addTimeline`|`characterId`、`summary`、`detail`、`appLabel`、`appEventId`、`data`、`createdAt`|",
  "|`memory.deleteTimeline` / `memory.removeTimeline`|`entryId`，或 `characterId` + `appEventId`|",
  "|`memory.suggest`|`characterId`、`content`、`type`、`importance`、`reason`|",
  "|`wallet.pay`|`amount`、`accountId`、`title`、`detail`、`category`、`relatedOrderId`|",
  "|`calendar.write`|`date`、`startTime`、`endTime`、`title`、`ownerType/ownerId/characterId`，也可传 `operation`|",
  "",
  "### 5.24 钱包付款",
  "",
  "外卖、购票、服务类 APP 可调用用户钱包扣款：",
  "",
  "```js",
  "const wallet = await AiPhone.wallet.get();",
  "const result = await AiPhone.wallet.pay({",
  "  amount: 50, accountId: wallet.accounts[0].id,",
  "  title: \"Float 外卖\", detail: \"冬阴功汤、椰汁饭\",",
  "  category: \"外卖\", relatedOrderId: \"order_001\"",
  "});",
  "if (!result.ok) await AiPhone.ui.toast(result.error || \"付款失败\");",
  "```",
  "",
  "需 `wallet.read` / `wallet.pay`。",
  "",
  "### 5.25 桥接现实（现实桥 × iPhone 快捷指令）",
  "",
  "小手机内置「现实桥」APP：用户用 iPhone 快捷指令把现实世界的信号（到家、离开某地、碰一下 NFC 贴纸、健康数据……）发进小手机；小手机也能把数据回传给快捷指令去执行现实动作（开灯、放音乐、触发任意快捷指令）。你的自定义 APP 可以接上这条管道，做出**真正能碰到现实**的 APP。",
  "",
  "四个能力：",
  "",
  "|能力|调用|权限|",
  "|-|-|-|",
  "|收：监听现实信号|`AiPhone.on(\"bridge.data\", handler)`|manifest `extensions.events` 声明 `bridge.data`|",
  "|发：回传给 iPhone 执行|`AiPhone.bridge.send({ type, payload })`|`bridge.send`|",
  "|查：读手机状态快照|`AiPhone.bridge.readState({ key })`|`bridge.read`|",
  "|唤：触发 iPhone 快捷指令并等结果|`AiPhone.tools.invoke(\"快捷动作名\", 参数)`|`chat.tools`|",
  "",
  "**收**：用户在现实桥里打开「允许自定义APP订阅」总开关（或在某条联动规则里勾选「广播事件」动作）后，每条进来的桥数据都会作为 `bridge.data` 事件广播。事件payload：`{ type, payload, processed, receivedAt }`——`type` 是快捷指令里自定的信号名，`payload` 是原始数据，`processed` 是规则加工后的文本（未加工时等于原文）。事件声明写 `background: true` 时，APP 没打开也会被临时拉起处理（同 5.18 的隐藏运行环境规则）。",
  "",
  "**发**：`AiPhone.bridge.send({ type: \"信号名\", payload: \"数据\" })` 把一条数据写进现实桥发件箱；用户 iPhone 上的「检查回传」快捷指令会取走它，并按信号名分支执行现实动作。`payload` 传对象会自动 JSON 序列化，最长 2000 字。",
  "",
  "**查**：现实桥支持用快捷指令自动化定期上传手机状态快照（电量、位置、日程等，用户自定义）。`AiPhone.bridge.readState({ key: \"battery\" })` 读单个快照（返回 `{ key, text, updatedAt }`，没有则 `null`）；不传 `key` 返回全部快照列表。",
  "",
  "> 现实桥的云端管道由用户在现实桥 APP 里自行配置；未配置时 `bridge.send` / `bridge.readState` 会抛错，请 catch 后引导用户先完成现实桥教程。",
  "",
  "#### 触发 iPhone 快捷指令并等待结果",
  "",
  "「发」是写发件箱等 iPhone 轮询取走；如果想**立刻**让 iPhone 跑一条快捷指令、甚至拿回它的执行结果（文本或截图），走用户在现实桥里登记的「快捷动作」——它们同时也是宿主工具，APP 可以直接按名调用：",
  "",
  "```js",
  "// \"打开微信并截图\" 是用户在现实桥→快捷动作里登记的名字",
  "const result = await AiPhone.tools.invoke(\"打开微信并截图\", {});",
  "if (result.success) {",
  "  console.log(result.data);                    // 文本结果",
  "  const shot = (result.mediaAttachments || [])[0];  // 图片结果（若该动作配置为回传图片）",
  "}",
  "```",
  "",
  "规则与边界：",
  "",
  "* 需要 `chat.tools` 权限；快捷动作**必须由用户自己在现实桥里登记并启用**（推送/邮件触发方式、是否等待结果、命令有效期都是用户配置的），APP 不能凭空创建——请在 APP 说明里写清「请先在现实桥登记名为 XX 的快捷动作」。",
  "* 推送模式需要用户点一下通知才开始执行；邮件模式配合 iOS 邮件自动化可免确认。",
  "* `tools.invoke` 会**等待执行结果**（等待上限 = 该动作的命令有效期，30 秒~15 分钟），期间 APP 要保持打开；超时或失败时 `result.success` 为 false、`result.error` 是原因。",
  "* 只发不等的场景（比如开灯）建议动作配置为「发出后立即返回」，或直接用 `bridge.send` 走发件箱。",
  "",
  "#### 完整闭环示例：「到家模式」",
  "",
  "目标：用户到家 → 你的 APP 被自动拉起、按自己的逻辑决定要干什么 → iPhone 自动执行（开灯、放歌…），角色还会在聊天室迎接TA。",
  "",
  "manifest 关键部分：",
  "",
  "```json",
  "{",
  "  \"permissions\": [\"app.data.read\", \"app.data.write\", \"bridge.send\", \"chat.write\", \"chat.requestReply\"],",
  "  \"extensions\": {",
  "    \"events\": [",
  "      {",
  "        \"event\": \"bridge.data\",",
  "        \"entry\": \"on-bridge-signal\",",
  "        \"background\": true,",
  "        \"description\": \"监听现实桥信号；到家信号触发到家模式。\"",
  "      }",
  "    ]",
  "  }",
  "}",
  "```",
  "",
  "APP 内 handler：",
  "",
  "```js",
  "AiPhone.on(\"bridge.data\", async function (evt) {",
  "  if (evt.type !== \"到家\") return;",
  "  // 1. 按自己的业务决定要做什么（读私有数据里的用户偏好等）",
  "  const prefs = await AiPhone.db.list(\"home_prefs\");",
  "  const scene = (prefs[0] && prefs[0].scene) || \"开灯+舒缓歌单\";",
  "  // 2. 回传给 iPhone：快捷指令读到「到家模式」信号后执行对应现实动作",
  "  await AiPhone.bridge.send({ type: \"到家模式\", payload: scene });",
  "  // 3. 顺手让角色知道TA到家了，在聊天室迎接（可选）",
  "  await AiPhone.chat.writeHistory({",
  "    characterId: prefs[0] && prefs[0].characterId,",
  "    role: \"system\", content: \"[到家模式APP] 用户刚到家，已自动执行：\" + scene,",
  "  });",
  "  await AiPhone.chat.requestReply({ characterId: prefs[0] && prefs[0].characterId });",
  "});",
  "```",
  "",
  "iPhone 侧两条快捷指令（用户按现实桥教程页配置，你只需在 APP 说明里写清信号名）：",
  "",
  "1. **自动化「到家」**：个人自动化 → 到达（家的位置）/ NFC 碰贴纸 → 运行现实桥教程里的「发送数据」快捷指令，信号名填 `到家`。",
  "2. **「检查回传」**：现实桥教程里的回传检查快捷指令，加一个分支——信号名是 `到家模式` 时，执行「设定家庭场景」（HomeKit 开灯）、「播放音乐」等现实动作。",
  "",
  "整条链路：**到家 → 快捷指令发信号 → 小手机拉起你的 APP → APP 决策后 `bridge.send` 回传 → 快捷指令执行现实动作 + 角色开口迎接**。把「到家」换成任何现实信号、把「开灯」换成任何快捷指令能做的事，就是你自己的创意了。",
  "",
  "### 5.26 多人联机（实时房间 + 云端共享）",
  "",
  "APP 可以让**不同用户的真人**互相联机：开房间实时对战/聊天，或通过云端共享数据做漂流瓶、排行榜这类异步玩法。需要声明 `online.play` 权限；联机只在用户**登录了联机账号**的站点可用（单机模式没有账号体系，调用会抛错，请 catch 后提示）。",
  "",
  "两套原语，按玩法选：",
  "",
  "|玩法形态|用哪层|例子|",
  "|-|-|-|",
  "|几个人同时在线、消息即时到|实时房间 `AiPhone.room.*`|狼人杀、谁是卧底、你画我猜、聊天室|",
  "|玩家不需要同时在线、靠公共数据池|云端共享 `AiPhone.cloud.*`|漂流瓶、排行榜、留言板、逛别人的店|",
  "",
  "#### 实时房间",
  "",
  "```js",
  "// 房主开房（拿到 4 位房号，展示给朋友输入）",
  "const room = await AiPhone.room.create({ title: \"狼人杀\", maxPlayers: 8 });",
  "showCode(room.code);            // 如 \"8A3F\"；room.selfUserId 是自己的联机身份",
  "",
  "// 其他玩家凭房号加入",
  "const joined = await AiPhone.room.join({ code: \"8A3F\" });",
  "",
  "// 收发消息（发给房内所有其他人；自己发的不会回环）",
  "AiPhone.on(\"room.message\", (msg) => { render(msg.from.name, msg.payload); });",
  "await AiPhone.room.send({ type: \"chat\", text: \"大家好\" });",
  "",
  "// 玩家进出（presence 自动维护）",
  "AiPhone.on(\"room.players\", ({ players }) => renderPlayerList(players));",
  "",
  "// 权威状态：只有房主能写，所有人（包括中途加入的）自动收到最新一份",
  "AiPhone.on(\"room.state\", ({ state }) => renderGame(state));",
  "if (room.isHost) await AiPhone.room.setState({ phase: \"night\", round: 1 });",
  "",
  "// 房主特权与退出",
  "await AiPhone.room.kick(playerId);   // 踢人（对方被移出且不能再进）",
  "await AiPhone.room.close();          // 关房",
  "await AiPhone.room.leave();          // 普通玩家退出",
  "AiPhone.on(\"room.closed\", ({ reason }) => showEnd(reason)); // host_closed / host_left / kicked",
  "```",
  "",
  "**房间事件需要在 manifest `extensions.events` 声明**（`room.message`、`room.players`、`room.state`、`room.closed`，按用到的声明），再用 `AiPhone.on` 监听。",
  "",
  "**架构规则（重要，照做能避开 90% 的联机 bug）**：",
  "",
  "* **权威逻辑放房主端**：谁是卧底的词、狼人杀的身份分配、回合判定，全部由房主的客户端计算，用 `room.setState` 下发；其他玩家只把自己的操作用 `room.send` 报给房主。不要让每个客户端各算各的。",
  "* 游戏画面**始终从 `room.state` 渲染**——新玩家进房自动收到最新 state，断线重连也能恢复。`room.send` 的消息只当\"事件\"用，不当\"状态\"用。",
  "* **断线重连是常态，不是异常**：手机锁屏/切后台会挂起网络连接（iOS 尤甚），恢复后自动重连。平台已做瞬断宽限——20 秒内的掉线不会触发 `room.players` 变化；但超过宽限的玩家会先消失再重现。**同一个 userId 重新出现 = 原玩家重连，不是新玩家**——游戏中途看到\"新\" userId 时，先查它是否已有座位，有座位就恢复而不是拒之门外。",
  "* 房主掉线约 50 秒后房间自动结束（所有人收到 `room.closed`，reason 为 `host_left`），请做好收尾 UI；本版本不支持房主迁移。",
  "* 一个 APP 同时只有一个房间连接；APP 关闭自动退房（房主关 APP = 关房）。",
  "* 限速：每人每秒最多 25 条、单条 16000 字符。你画我猜的笔画请**攒批发送**（如每 100ms 一批坐标）。",
  "* 适合回合制与低频同步（手机网络延迟 200-500ms）；**不适合**动作类帧同步对战。房主是普通客户端，防作弊能力有限，别做高价值竞技排名。",
  "",
  "#### 带角色上桌（人和 AI 角色同场玩）",
  "",
  "联机不只是真人对真人：每个玩家还可以把**自己的角色**带进房间一起玩（比如两个用户加各自的角色凑一桌狼人杀）。核心原则：**角色由它主人的客户端驱动**——人设、记忆、API key 都只在主人设备上，轮到角色行动时由主人的客户端本地调 `ai.generate`（传 `characterId`，宿主自动组装完整人设），把生成结果当普通玩家操作 `room.send` 出去。其他玩家只看到角色的发言，永远拿不到人设；token 由角色主人消耗。需要 `ai.generate` + `characters.read` 权限。",
  "",
  "```js",
  "// 进房后把带的角色报给房主；房主把它记成一个虚拟座位写进 state：",
  "// state.seats = [{ seatId, kind: \"human\"|\"character\", ownerUserId, name, charId }]，state.turn = seatId",
  "await AiPhone.room.send({ type: \"bring\", name: \"小红\", charId: chosenId });",
  "",
  "// 每个客户端收到 state：轮到\"我拥有的角色座位\"就代它行动",
  "AiPhone.on(\"room.state\", async ({ state }) => {",
  "  const seat = state.seats.find(s => s.seatId === state.turn);",
  "  if (seat && seat.kind === \"character\" && seat.ownerUserId === me.userId && !generating) {",
  "    generating = true;",
  "    const result = await AiPhone.ai.generate({",
  "      characterId: seat.charId,",
  "      instruction: `你在玩狼人杀，当前局面：${describe(state)}。请以角色身份发言（80字内，只输出发言）。`,",
  "    });",
  "    await AiPhone.room.send({ type: \"action\", seatId: seat.seatId, text: result.text });",
  "    generating = false;",
  "  }",
  "});",
  "```",
  "",
  "两类 AI 参与者别弄混：**玩家自带角色**（上面这种）由各自主人的客户端驱动；**无主 NPC**（系统裁判、补位路人）没有主人，统一由房主端生成并写进 state。另外要处理：角色主人掉线会\"卡回合\"，房主端做超时跳过（60 秒无响应自动弃权）；生成期间加锁防止重复触发。",
  "",
  "#### 云端共享（异步玩法）",
  "",
  "```js",
  "// 漂流瓶：扔一个 / 随机捞一个别人的（捞走即独占，不会两个人捞到同一个）",
  "await AiPhone.cloud.put({ collection: \"bottles\", data: { text: \"有人在吗\" } });",
  "const bottle = await AiPhone.cloud.takeRandom({ collection: \"bottles\" });",
  "if (bottle) show(bottle.ownerName, bottle.data.text);   // 可能为 null（池子空了）",
  "",
  "// 排行榜：sortKey 排序取前 N",
  "await AiPhone.cloud.put({ collection: \"scores\", data: { score: 9800 }, sortKey: 9800 });",
  "const top = await AiPhone.cloud.list({ collection: \"scores\", orderBy: \"sortKey\", limit: 10 });",
  "",
  "// 自己的数据：列出 / 修改 / 删除（只能动自己的）",
  "const mine = await AiPhone.cloud.list({ collection: \"bottles\", mine: true });",
  "await AiPhone.cloud.update({ id: mine[0].id, data: { text: \"改过了\" } });",
  "await AiPhone.cloud.delete(mine[0].id);",
  "```",
  "",
  "规则：数据按 APP 隔离（读不到其他 APP 的）；每条 `data` 上限 8000 字符；每个用户在本 APP 最多 200 条；`list` 单次最多 50 条。每条文档自带 `ownerId` / `ownerName` / `createdAt`。",
  "",
  "> 内容安全提醒：联机房间和云端共享都是真人对真人的通道。宿主内置举报通道：`AiPhone.cloud.report({ id, reason })` 举报一条云端内容（如捞到的漂流瓶）、`AiPhone.room.report(reason)` 举报当前房间——请在相应 UI 里放上举报按钮（房主踢人用 `kick`），不要做鼓励陌生人私密交换个人信息的玩法。",
  "",
  "---",
  "",
  "## 6. 权限清单",
  "",
  "`permissions` 只声明实际会用到的能力。",
  "",
  "### 6.1 常用",
  "",
  "* `app.data.read` / `app.data.write`：读写本 APP 私有数据。",
  "* `app.assets.read`：读取本 APP 随包资源。",
  "* `app.manifest.read`：读取 manifest 和 SDK 能力摘要。",
  "* `characters.read`：读取角色基础信息。",
  "* `ai.generate`：让指定角色基于 APP 任务生成内容，但不自动发送到聊天室。",
  "* `chat.read`：读取授权范围内的聊天会话和历史。",
  "* `chat.read.background`：APP 未打开时后台监听聊天消息；后台 handler 需要读聊天历史时也可用它。",
  "* `chat.write` / `chat.sendMessage`：发送普通聊天消息，或通过 `chat.history` 写入 APP 事件历史。",
  "* `chat.sendCard`：向角色聊天室发送 APP 卡片。",
  "* `chat.requestReply`：请求角色在聊天室里根据已写入的聊天历史或 APP 卡片回复。",
  "* `ui.toast`：显示短提示。",
  "* `ui.notification`：显示通知。",
  "",
  "### 6.2 角色 / 用户 / 记忆",
  "",
  "* `characters.state.read` / `characters.state.write`：读写角色状态。",
  "* `characters.relations.read`：读取角色关系。",
  "* `user.profile.read` / `user.persona.read` / `user.preferences.read`：读取用户资料、人设、偏好。",
  "* `memory.readCore` / `memory.readLongTerm` / `memory.readShortTerm` / `memory.search`：读取或搜索记忆。",
  "* `memory.write`：写入角色记忆。",
  "* `memory.suggest`：提交记忆写入建议。",
  "",
  "### 6.3 进阶能力",
  "",
  "* `ai.chat` / `ai.embed` / `ai.classify`：高级 AI 会话、向量、分类。",
  "* `ai.generateImage`：调用宿主已配置的生图 API 生成一张图片。",
  "* `network.fetch`：访问 manifest `network.allowedDomains` 里声明的域名。",
  "* `voice.tts` / `voice.stt` / `voice.clone` / `voice.readProfiles`：语音生成、识别、克隆、读取声音配置。",
  "* `chat.contacts.write`：修改联系人状态（拉黑、解除拉黑、免打扰）。",
  "* `chat.tools`：注册 AI 可调用工具。",
  "* `world.read`：读取世界书。",
  "* `calendar.read` / `calendar.write`：读写日程。",
  "* `media.pick` / `media.save`：选择或保存媒体。",
  "* `media.put` / `media.get` / `media.delete`：媒体库,音频/图片以 Blob 存储换取引用,db 记录里只存引用。",
  "* `voice.play` / `voice.stopPlayback` / `voice.pausePlayback` / `voice.resumePlayback`：把音频播放委托给宿主(iOS 上必用,见 5.9)。",
  "* `notifications.read` / `notifications.write`：读取本 APP 通知和红点 / 创建通知、设置桌面红点。",
  "* `tasks.schedule`：创建后台定时任务（浏览器关闭时不运行，重开后补跑到期任务）。",
  "* `wallet.read` / `wallet.pay`：读取钱包余额和可用付款账户 / 从用户钱包扣款。",
  "* `bridge.send`：通过现实桥向 iPhone 快捷指令回传数据（见 5.25）。",
  "* `bridge.read`：读取现实桥的手机状态快照（见 5.25）。",
  "* `online.play`：多人联机——实时房间与云端共享数据（见 5.26）。",
  "",
  "---",
  "",
  "## 7. 前端要求",
  "",
  "1. 输出**可直接运行**的 HTML/CSS/JS，不要求用户安装 npm 或构建工具。",
  "2. 页面跑在手机尺寸 iframe 中，必须适配**竖屏和触摸**操作。",
  "3. 宿主会在**右上角**悬浮一个半透明的系统返回胶囊（点它回桌面）。**不要把关键按钮放右上角**，以免重叠；左上角可正常放自己的标题或返回。",
  "4. 内容很多时，在 APP 内部做滚动区域，避免横向滚动。",
  "5. 不要使用会要求跨域权限的远程脚本；图片、字体、CSS 建议放进 `assets/`。",
  "",
  "建议使用安全区变量。骨架只管左右和底部，**顶部留给下面的方案二选一**：",
  "",
  "```css",
  "html, body {",
  "  width: 100%;",
  "  min-height: 100%;",
  "  margin: 0;",
  "}",
  "* { box-sizing: border-box; }",
  ".app {",
  "  min-height: 100dvh;",
  "  padding: 0 16px var(--ai-phone-app-safe-bottom, 24px);",
  "  /* padding-top 见下面「顶部怎么摆」，A / B 二选一 */",
  "}",
  "button, input, textarea { font: inherit; }",
  "button { min-height: 44px; }",
  "```",
  "",
  "宿主会把实测的安全区数值注入这些变量（并在显示模式变化时更新，同时派发 `aiphone:safe-area-change` 事件），没注入到之前由回退值兜底。注意：这些变量只用来给**内容**让位（按钮、标题挪进安全区），不要用它收缩画布——背景层应始终铺满整个页面。",
  "",
  "### 顶部怎么摆（A / B 二选一）",
  "",
  "**先按这条选**：APP 有自己的顶栏（标题、图标、切换按钮）→ 用 **方案 A**；顶部直接就是内容（整屏画布、一进来就开始的列表、沉浸式背景）→ 用 **方案 B**。",
  "",
  "多数 APP 属于前者，**默认用 A**。胶囊只占右上角一小块，左边和中间整片是空的；整体让到胶囊下面会让顶部留出一大条白，把标题压得很低。",
  "",
  "**方案 A · 自己的顶栏与宿主胶囊同排**",
  "",
  "```css",
  ".topbar {",
  "  position: fixed;                                   /* 别用 absolute：.app 没设 position，会以 body 为准，一滚就跑 */",
  "  top: var(--ai-phone-app-bar-top, 56px);            /* 与胶囊同一行 */",
  "  left: 16px;                                        /* 左侧没有宿主元素，随便用 */",
  "  right: var(--ai-phone-app-bar-clear-right, 96px);  /* 只避开右侧胶囊的水平占位 */",
  "  min-height: var(--ai-phone-app-bar-height, 30px);",
  "}",
  "/* 顶栏比胶囊高是允许的（比如标题 + 副标题两行），它会向下长。",
  "   所以内容区要让开的是「胶囊那一行的顶 + 你顶栏的实际高度」，不是 bar-top 本身，",
  "   否则内容会被顶栏压住。高度写死或用 JS 实测都行。 */",
  ".app { padding-top: calc(var(--ai-phone-app-bar-top, 56px) + 顶栏实际高度 + 12px); }",
  "```",
  "",
  "**方案 B · 整体让到胶囊下面**",
  "",
  "```css",
  ".app { padding-top: var(--ai-phone-app-safe-top, 88px); }",
  "```",
  "",
  "---",
  "",
  "## 8. 实现流程与给 AI 的提示词模板",
  "",
  "### 8.1 推荐实现流程",
  "",
  "1. 先做单 HTML 原型，跑通 UI 和交互。",
  "2. 再补 `manifest.json` 和 `icon.png`。",
  "3. 只声明真实用到的权限。",
  "4. 需要和聊天深度联动时，再补 `presets.json`。",
  "5. 用户先本机测试，确认 APP 卡片、聊天感知、记忆写入都符合预期，再发布市场。",
  "",
  "### 8.2 请 AI 生成 APP 时可以这样提需求",
  "",
  "> 请为小手机应用市场生成一个完整自定义 APP 包，遵守上面的 SDK 和文件结构。我的 APP 想法是：",
  ">",
  "> 【在这里写你的想法】",
  ">",
  "> 请输出所有文件内容，至少包含 manifest.json、index.html、icon.png 的设计建议。如果需要声明场景预设，也一起输出 presets.json。index.html 必须能直接运行，UI 要适配手机竖屏，所有 SDK 调用都要使用 window.AiPhone。",
  "",
];

export const CUSTOM_APP_CREATOR_GUIDE_MD = CUSTOM_APP_CREATOR_GUIDE_LINES.join("\n");
